<a href="https://colab.research.google.com/github/Lilchoto3/DS-Unit-3-Sprint-1-Software-Engineering/blob/master/module1-python-modules-packages-and-environments/LS_DS_311_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
# To test my functions, I'll use the water pump data from the Kaggle challenge 
# from unit 2
DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/'
df = pd.merge(pd.read_csv(DATA_PATH+'waterpumps/train_features.csv'), 
              pd.read_csv(DATA_PATH+'waterpumps/train_labels.csv'))

print(df.shape)
df.head()

(59400, 41)

      id  amount_tsh  ... waterpoint_type_group    status_group
0  69572      6000.0  ...    communal standpipe      functional
1   8776         0.0  ...    communal standpipe      functional
2  34310        25.0  ...    communal standpipe      functional
3  67743         0.0  ...    communal standpipe  non functional
4  19728         0.0  ...    communal standpipe      functional

[5 rows x 41 columns]

In [25]:
# install my module and use its functions
# module can be found at https://test.pypi.org/project/lambdata-zacharyluck/
# source code can be found at https://github.com/Lilchoto3/lambdata-lilchoto3

!pip install -i https://test.pypi.org/simple/ lambdata-zacharyluck==1.0.1

Looking in indexes: https://test.pypi.org/simple/
Collecting lambdata-zacharyluck==1.0.1
  Downloading https://test-files.pythonhosted.org/packages/96/af/0ba0c4b9d678e19769f6a7684163cedb0c8497b99838b5c5a62c81ecede2/lambdata_zacharyluck-1.0.1-py3-none-any.whl
Installing collected packages: lambdata-zacharyluck
  Found existing installation: lambdata-zacharyluck 1.0
    Uninstalling lambdata-zacharyluck-1.0:
      Successfully uninstalled lambdata-zacharyluck-1.0
Successfully installed lambdata-zacharyluck-1.0.1

In [34]:
# import the file with the functions and make sure they're there
from my_lambdata import lambdata

dir(lambdata)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add_column',
 'pd',
 'split_datetime']

In [35]:
# to use the datetime function, I actually need datetimes in my dataframe
df['date_recorded'] = pd.to_datetime(df['date_recorded'], infer_datetime_format=True)

print(df['date_recorded'].dtype)
df.head()

datetime64[ns]

      id  amount_tsh  ... waterpoint_type_group    status_group
0  69572      6000.0  ...    communal standpipe      functional
1   8776         0.0  ...    communal standpipe      functional
2  34310        25.0  ...    communal standpipe      functional
3  67743         0.0  ...    communal standpipe  non functional
4  19728         0.0  ...    communal standpipe      functional

[5 rows x 41 columns]

In [36]:
# prove that split_datetime works; this should split any and all
# datetime dtyped columns into three columns, of which should be the month, day
# and year
df = lambdata.split_datetime(df)
df.head()

      id  amount_tsh  ... date_recorded_day date_recorded_year
0  69572      6000.0  ...                14               2011
1   8776         0.0  ...                 6               2013
2  34310        25.0  ...                25               2013
3  67743         0.0  ...                28               2013
4  19728         0.0  ...                13               2011

[5 rows x 44 columns]

In [39]:
# cool, now prove that add_column works
df = lambdata.add_column(df, list(range(df.shape[0])), 'index_two_electric_boogaloo')
# I needed to list-ify the range function because range returns an object
# not a list; however the object can be list-ified easily, so that would
# be sometime to add into the add_column function to catch if a range object
# is given for series.

df.head()

      id  amount_tsh  ...    status_group index_two_electric_boogaloo
0  69572      6000.0  ...      functional                           0
1   8776         0.0  ...      functional                           1
2  34310        25.0  ...      functional                           2
3  67743         0.0  ...  non functional                           3
4  19728         0.0  ...      functional                           4

[5 rows x 42 columns]